# -*- coding: utf-8 -*-
"""automate_ahmad_riki_andreas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBXP4KlUNcBIUYubzGDYzxhuZcR51wYa
"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

def load_data():
    df = pd.read_csv("data.csv")

    if "Unnamed: 32" in df.columns:
        df = df.drop("Unnamed: 32", axis=1)

    df["diagnosis"] = df["diagnosis"].map({
        "B": 0,
        "M": 1
    })

    return df

df = load_data()

df.head()

def preprocessing():
    df = load_data()

    X = df.drop(["id", "diagnosis"], axis=1)
    y = df["diagnosis"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = preprocessing()

print("Preprocessing berhasil")
print("Shape X_train:", X_train.shape)
print("Shape X_test:", X_test.shape)
print("Jumlah data train:", len(y_train))
print("Jumlah data test:", len(y_test))

import os

os.makedirs("Eksperimen_SML/dataset_raw", exist_ok=True)
os.makedirs("Eksperimen_SML/preprocessing", exist_ok=True)

df.to_csv(
    "Eksperimen_SML/dataset_raw/breast_cancer.csv",
    index=False
)

print("RAW DONE")

df_preprocessed = df.copy()

df_preprocessed.to_csv(
    "Eksperimen_SML/preprocessing/breast_cancer_preprocessing.csv",
    index=False
)

print("PREPROCESSING DONE")

!ls -R Eksperimen_SML